//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotnet_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int idUsuario { get; set; }
        public string nmUsuario { get; set; }
        public string nmLogin { get; set; }
        public string dsEmail { get; set; }
        public string cdCPF { get; set; }
        public Nullable<int> idEmpresa { get; set; }
    }
}
